app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
/*
Route::get('/', function () {
    return view('welcome');
});

Route::get('clasificacion_option', function(){
	
});

Route::resource('/pregunta', 'preguntaController');

Route::resource('video', 'videoController');

Route::resource('/cuestionario', 'cuestionarioController');


//Route::post('/clasificacionVideo/store','clasificacionVideoController@store')
Route::resource('/clasificacionVideo', 'clasificacionVideoController');

Route::post('/upload', function(){
     if(Input::hasFile('archivo')) {
          Input::file('archivo')
               ->move('carpetarArchivos','NuevoNombre');
     }
     return Redirect::back(('/');
});
*/
//Route::get('/registro', 'Auth\AuthController@getRegister');
//Route::post('/registro', 'Auth\AuthController@postRegister');

routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});



Auth::routes();

//Route::get('/', 'HomeController@index');

//Rutas del acceso a usuarios
Route::get('login', [
			'uses' => 'LoginController@login',
			'as' => 'login'
	]);
Route::post('login', 'LoginController@posLogin');
Route::get('logout', 'LoginController@getLogout');


//Rutas del registro a usuarios
Route::get('/registro', 'LoginController@getRegister');
Route::post('/registro', 'LoginController@create');

Route::resource('/video/download', 'videoController@download');

//Rutas de usuarios Tipo - Alumnos
Route::group( ['prefix' => 'alumno'] , function(){


	Route::get('/', function () {
   					 return view('UsuarioRol.alumno', ['Tipo_Acceso' => 'alumno']);
	});
	
	Route::resource('video', 'videoController');

	Route::resource('cuestionario', 'cuestionarioController');

	Route::resource('videoCalificacion', 'videoCalificacionController');

	Route::resource('preguntaRespuesta', 'preguntaRespuestaController');
	//Route::post('preguntaRespuesta', 'preguntaRespuestaController@store');

	Route::resource('usuarioTest', 'usuarioTestController');


});



//Rutas de usuario Tipo - Docente
Route::group( ['prefix' => 'docente'] , function(){

	Route::get('/', function () 
	{
		return view('UsuarioRol.docente', ['Tipo_Acceso' => 'docente']);
	});

	Route::resource('video', 'videoController');

	Route::resource('videoCuestionario', 'videoCuestionarioController');

	Route::resource('cuestionario', 'cuestionarioController');

	Route::resource('clasificacionVideo', 'clasificacionVideoController');
	
	Route::resource('pregunta', 'preguntaController');

	Route::resource('usuarioTest', 'usuarioTestController');

	Route::resource('preguntaRespuesta', 'preguntaRespuestaController');

});



//Rutas de usuario Tipo - Administrador
Route::group(['prefix' => 'administrador']  , function(){
//Route::group(['middleware' => 'administrador']  , function(){
	
	Route::get('/', function () 
	{
		return view('UsuarioRol.administrador');
	});

	Route::get('busquedaVideos', 'videoController@busquedaVideos');
	Route::resource('video', 'videoController');

	Route::resource('cuestionario', 'cuestionarioController');

	Route::resource('clasificacionVideo', 'clasificacionVideoController');

	Route::resource('pregunta', 'preguntaController');

	Route::resource('videoCuestionario', 'videoCuestionarioController');

	Route::resource('preguntaRespuesta', 'preguntaRespuestaController');

	Route::resource('usuarioTest', 'usuarioTestController');

	Route::resource('user', 'userController');
	
});

app/video.php
<?php

namespace Biobiblioteca;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class video extends Model
{
    //create consulta para tabla de videos
    protected $table = 'videos';

    protected $fillable = ['url', 'titulo', 'ancho', 'alto', 'framerate', 'duracion', 'clasificacion', 'descripcion'];

    protected $primaryKey = 'idVideo';

    public $timestamps = true;

    
    public function scopeTitulo($query, $titulo = ""){

    	//dd('scope: '.$titulo);
    	if(trim($titulo) != ""  ){
    		$query= DB::table('videos')
                ->join('clasificaciones', 'videos.clasificacion', '=', 'clasificaciones.idClasificacion')
                ->select('videos.idVideo','videos.titulo','videos.descripcion','videos.duracion', 'clasificaciones.Nombre')
                ->where('videos.titulo', "like" , '%'.$titulo.'%')
                ->orWhere('videos.descripcion', "like", '%'.$titulo.'%')
                ->orderBy('idVideo', 'ASC');
     	}else
        {
            $query= DB::table('videos')
                    ->join('clasificaciones', 'videos.clasificacion', '=', 'clasificaciones.idClasificacion')
                    ->select('videos.idVideo','videos.titulo','videos.descripcion','videos.duracion', 'clasificaciones.Nombre')
                    ->orderBy('videos.idVideo', 'ASC');
               
        }

        return $query;
    }

    public function scopeClasificacion($query, $idClasificacion){

        $Filtro_Clasificacion = $idClasificacion;
        if($idClasificacion != 0){
            $query = DB::table('clasificaciones')
                            ->where('clasificaciones.idClasificacion',$idClasificacion);
        }
    }
    
}

app/Http/Controllers/videoController.php
<?php

namespace Biobiblioteca\Http\Controllers;

use Biobiblioteca\video;
use Biobiblioteca\cuestionario;
use Biobiblioteca\Http\Requests;
use Biobiblioteca\clasificacionVideo;
use Biobiblioteca\calificacionVideo;
use Biobiblioteca\usuarioTest;

use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;

//use Auth;
use FFmpegMovie;

class videoController extends Controller
{
    
    public function index(Request $request)
    {
       
        $video = video::titulo($request->get('titulo'))
                        ->paginate(10);

        $clasificaciones = clasificacionVideo::pluck('Nombre','idClasificacion');
        
        if($request->ajax() ){
          return view ('video.viewIndex', [ 'videos' => $video]);
        }

        return view ('video.listadovideo', [ 'videos' => $video, 'clasificaciones' =>  $clasificaciones]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $clasificaciones = clasificacionVideo::pluck('Nombre','idClasificacion');
        return view('video.prueba',  [ 'clasificaciones' => $clasificaciones]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
         
        $this->validate($request,[
            'archivo'=> 'required',
            'Listaclasificacion' => 'required',
        ]);

        //obtenemos el campo file definido en el formulario
        $file = Input::file('archivo');
        $nombre = Input::file('archivo')->getClientOriginalName();
         
       
        //Se guarda el video en el disco seleccionado
        $disk = \Storage::disk('uploads');  
         
         $nameFileSave =  time().'_'.$nombre;   
         $disk->put( $nameFileSave, \File::get($file),'public');
          
       // $fileRecover = public_path()."/videos/".$nameFileSave;

      if($disk->exists($nameFileSave))
        {
           //Recuperar el archivo del disco almacenado
          $filePath = $disk-> getDriver()-> getAdapter()-> getPathPrefix();
          
          $movie = new FFmpegMovie($filePath.$nameFileSave);
          $duracion = $movie-> getDuration();
          $frames = $movie-> getFrameCount();
          $width = $movie-> getFrameWidth();
          $height = $movie-> getFrameHeight();

          //Modelo que recopila la informacion que sera enviada la base de datos
          $entry = new video([
             'url' => $filePath.$nameFileSave,
             'titulo' => Input::get('titulo'),
             'ancho' => $width,
             'alto' => $height,
             'framerate' => $frames,
             'duracion' => $duracion,
             'clasificacion' => Input::get('Listaclasificacion'),
             'descripcion' => Input::get('descripcion')
           ]);
           $entry->save();

           $authRol= \Auth::user()->role;
         
          //Devuelve el resultado a la misma pagina 
          Session::flash('success', 'Archivo Subido Correctamente '.$nombre);
          return redirect()->to($authRol.'/video');
  
        }
        else
        {
          return "No se encontro : ".$nameFileSave;
        }
         
    }


    /**
     * Display the specified resource.
     */
    public function show(Request $request,$idVideo)
    {
        //Extrae la URL y la particiona para buscar en la ubicacion correcta el video
        $path = $request->url();
        //$array_Path = explode('/', "http://ibhu.noip.me:6080/index.php/administrador/usuarioTest");
        $array_Path = explode('/', $path);
        $URL_Path = $array_Path[0].'//'.$array_Path[2];
        
        $urlPublic = $URL_Path; //'http://pruebalaravel';

        $videoFind = video::find($idVideo);
        
        $RecuperarUrl = DB::table('videos')
                                ->select('url')
                                ->where('idVideo',$idVideo)
                                ->first();

        $values = $RecuperarUrl->{'url'}; 
        
        $nameExt = explode('/', $values );

        $UrlFile = '/'.$nameExt[6].'/'.$nameExt[7];

        $calificarVideo = calificacionVideo::pluck('calificacion','idCalificacion_Video');

        $linkVideomp4 = $urlPublic.$UrlFile;
        //$linkVideoOgg = str_replace('mp4','ogg',$linkVideomp4);
        //Se valida que el usuario no haya finalizado el cuestionario
        $idUser = \Auth::id();

        $findTest = DB::table('usuarioTest')
                            ->select(DB::raw('count(usuarioTest.idUsuario) as totRegistros, usuarioTest.idCuestionario'))
                            ->where('usuarioTest.idUsuario', $idUser)
                            ->where('usuarioTest.idVideo', $idVideo)
                            ->get();
        
        $cuestionarioRespondidoTot = (int) $findTest[0]->totRegistros;
        //dd($findTest);
        //Se busca en la tabla de resultados si el usuario ya ha respondido el cuestionario
        if( $cuestionarioRespondidoTot > 0){
          //Cuando ya ha sido evaluado unicamente muestra el video
          return view('video.loadVideo',['detalleVideo' => $videoFind, 
                                          'linkVideo' => $urlPublic.$UrlFile,
                                           'evaluarVideo' => $calificarVideo,
                                        ]);
         
        }else{
          
          /*
          CONSULTA FINAL - ACTUALIZAR HOY 07 04 2017
            SELECT cp.idCuestionario, cp.idPregunta, p.Pregunta, p.RespuestaA, p.RespuestaB, p.RespuestaC, p.Resp_Correcta, pr.respuesta 
            From cuestionario_pregunta cp 
            INNER JOIN preguntas p on p.idPregunta = cp.idPregunta 
            LEFT JOIN pregunta_respuesta pr on pr.idPregunta = p.idPregunta and pr.idUsuario = 3 
            LEFT JOIN cuestionario_Video cv on cv.idCuestionario = cp.idCuestionario and cv.idVideo = 2
            WHERE cp.idCuestionario = 1
          */
          $idCuestionario = \DB::table('cuestionario_Video as cv')
                                ->select('cv.idCuestionario')
                                ->where('cv.idVideo', $idVideo)
                                ->first();

          if($idCuestionario !== null){

            $questions = \DB::table('cuestionario_pregunta AS cp')
                             ->join('preguntas AS p', 'p.idPregunta', '=', 'cp.idPregunta')
                             ->leftJoin('pregunta_respuesta AS pr', function ( $join ) use ($idUser) {
                                        $join->on('pr.idPregunta', '=', 'p.idPregunta');
                                        $join->on('pr.idUsuario', DB::raw($idUser));
                             })
                             ->leftJoin('cuestionario_Video AS cv', function( $join ) use ($idVideo) {
                                        $join->on('cv.idCuestionario', '=', 'cp.idCuestionario');
                                        $join->on('cv.idVideo', DB::raw($idVideo));
                             })
                             ->select('cp.idCuestionario', 'cp.idPregunta','p.Pregunta','p.RespuestaA','p.RespuestaB','p.RespuestaC','p.Resp_Correcta','pr.respuesta','p.solucion')
                             ->where('cp.idCuestionario',$idCuestionario->idCuestionario)
                             ->paginate(15);

            $titCuestionario = \DB::table('cuestionarios as c')
                            ->select('c.Titulo','c.idCuestionario')
                             ->where('c.idCuestionario',$idCuestionario->idCuestionario)
                            ->first();
            
            if($request->ajax() ){
              //dd('aqui estoy');
              return  view('video.loadPreguntasTest', ['question' => $questions ]);
            }
          
            return view('video.playVideo', ['detalleVideo' => $videoFind, 
                                            'linkVideo' => $urlPublic.$UrlFile,
                                            //'linkVideoOgg' => $linkVideoOgg,
                                            'evaluarVideo' => $calificarVideo,
                                            'question' => $questions,
                                            'tituloCuestionario' => $titCuestionario
                                            ] );
          }
          else{
            return redirect()->back()->with('success', 'El video no tiene un cuestionario seleccionado');
          }

        }
        
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Request $request,$idVideo)
    {

         //Extrae la URL y la particiona para buscar en la ubicacion correcta el video
        $path = $request->url();
        $array_Path = explode('/', $path);
        $URL_Path = $array_Path[0].'//'.$array_Path[2];


        //Busca el video en la base de datos
        $videoFind = video::find($idVideo);
        $RecuperarUrl = DB::table('videos')
                                ->select('url')
                                ->where('idVideo',$idVideo)
                                ->first();

        $values = $RecuperarUrl->{'url'}; 
        
        $nameExt = explode('/', $values );

        $urlVideo = Storage::url( $nameExt[8] );
        //~ dd($urlVideo);


        //$contents = Storage::disk('uploads')->setVisibility( $nameExt[8], 'public' );
        $urlVideo_Ogg = str_replace('mp4', 'ogg', $urlVideo);

        $urlPublic = $URL_Path; //'http://pruebalaravel';
        $calificarVideo = calificacionVideo::pluck('calificacion','idCalificacion_Video');

         //Obtener las preguntas para un cuestionario.
        $questions = DB::table('cuestionario_Video')
                        ->join('cuestionario_pregunta', 'cuestionario_pregunta.idCuestionario', '=', 'cuestionario_Video.idCuestionario')

resources/views/video/addCuestionario.blade.php
@extends('layouts.master');

@section('title', 'BioVideoteca >> Videos')

@section('breadcrumbs')

@endsection

@section('content')
 @if(Session::has('success'))
        <h2>{!! Session::get('success') !!}</h2>
@endif

<div class="col-lg-6 col-xs-12 col-sm-12">
 <!-- BEGIN PORTLET-->
    <div class="portlet light bordered">
       <div class="portlet-title">
         <div class="caption">
            <span class="caption-subject font-dark bold uppercase">VIDEO</span>
        </div>

        </div>
        <div class="portlet-body">
           <video id="laracasts-video_html5_api" class="vjs-tech" preload="auto" height="340" width="450" controls autoplay>
              <source src="{{ $linkVideo }}" type="video/mp4">
              <source src="{{ $linkVideoOgg }}" type="video/ogg">
           </video>
           <div class="caption">
            <span class="caption-subject font-dark bold uppercase"> {{ $videoDetail->descripcion }} </span>
           </div>
        </div>
    </div>
 </div>
 <div class="col-lg-6 col-xs-12 col-sm-12">
 <!-- BEGIN PORTLET-->
    <div class="portlet light bordered">
       <div class="portlet-title">
         <div class="caption">
            <i class="icon-share font-red-sunglo hide"></i>
            <span class="caption-subject font-dark bold uppercase">Video Editar</span>
         </div>
        </div>
        <div class="portlet-body">
           
            {{ Form::open(array('route' => 'videoCuestionario.store' )) }}
            <input type="hidden" name="_token" value="{{{ csrf_token() }}}"/> 
        
        <p>
           
            {{ Form::label('Editar el titulo del Video') }}
            {{ Form::text('nombre',$videoDetail->titulo,array('class'=>'form-control')) }}
            <input type="hidden" name="idVideo" value="{{ $idVideoVal }}"/> 
           
        </p>
        
        <p>
            {{ Form::label('Cuestionàrio') }}
            {{ Form::select('lstCuestionarios', $listaCuestionario, null, array('disabled' => 'disabled','class' => 'form-control')) }}
        </p>    

        <p>
            {{ Form::submit('Agregar', array('class'=>'btn btn-primary')) }}

            <button type="button" class="btn btn-default"><a href="/index.php/{{ Auth::user()->role }}">Salir</a></button>
        </p>
    {{ Form::close() }}
         
        </div>
    </div>

 
 </div>


@endsection

@section('page_script') 
   <script>
    $(document).ready(function(){
        //Actualiza el logo de la aplicacion de Videoteca
        var currentPage = window.location.href.split('/');
        var path = currentPage[0].split('.')[0] + '//' + currentPage[2].split('.')[0];
        var urlLogo = path + '/assets/layouts/layout6/img/logo1.png';
        $('#logoVideoteca').attr('src', urlLogo);

    });
</script>
@endsection

resources/views/video/formRespuestaAlumno.blade.php
	<input type="hidden" name="respuestaCorrecta" id="respuestaCorrecta" value="{{ $item->Resp_Correcta }}">
    
    <input type="hidden" name="idPregunta" id="idPregunta" value="{{ $item->idPregunta }}">
    
    @if($item->respuesta)
    <input type="text" name="respAlumno" id="respAlumno-{{ $item->idPregunta }}" value="{{ $item->respuesta }}" class="form-control" size="3" disabled="disabled">
    @else
     <input type="text" name="respAlumno" id="respAlumno-{{ $item->idPregunta }}" value="{{ $item->respuesta }}" class="form-control" size="3">
      <a href="" class="send-respuesta" style="color:red">Guardar respuesta</a>
    @endif
    <input type="hidden" id="token" value="{{ csrf_token() }}">
    
    <input type="hidden" name="idCuestionario" id="idCuestionario" value="{{ $item->idCuestionario }}">
    
    <input type="hidden" name="hidden_addRespTest" id="hidden_addRespTest" value="{{url('/preguntaRespuesta/store')}}">
    
    <input type="hidden" name="hiddenRol" id="hiddenRol" value="{{Auth::user()->role}}">
    
    <input type="hidden" name="solucion" id="solucion" value="{{ $item->solucion }}" class="form-control" visible= false>
    
    

resources/views/video/listadovideo.blade.php
@extends('layouts.master');

@section('title', 'BioVideoteca >> Videos')

@section('breadcrumbs')

@endsection

@section('content')
<div class="portlet-body">
 	<div class="table-responsive">
 	    <div class="portlet box purple">
	 	    <div class="portlet-title">
				<div class="caption">
	                <i class="fa fa-globe"></i>Listado de Videos 
				</div>
				<div class="tools"> </div>
	        </div>
	        <div class="portlet-body">
	        	<div class="panel-body">
					{!! Form::open(['route'=> 'video.index', 'method'=> 'GET', 'class'=> 'navbar-form navbar-left pull-right', 'role'=> 'search']) !!}
						<div class="form-group">
							{!! Form::text('titulo', null, ['class' => 'form-control', 'placeholder' => 'Buscar por Titulo' ]) !!}
							{!! Form::select('list_clasificacion', $clasificaciones, null, ['class' => 'form-control', 'placeholder' => 'seleccione']) !!}
						</div>
						<button type="submit" class="btn btn-default">Buscar</button>
					{!! Form::close() !!}
				</div>
				<div class="table-responsive2">
					@include('video.viewIndex')
				</div>
			</div>
		</div>
	</div>
	
</div>
@endsection

@section('page_script')	
	<script>
	$(document).ready(function(){
		//Actualiza el logo de la aplicacion de Videoteca
        var currentPage = window.location.href.split('/');
        var path = currentPage[0].split('.')[0] + '//' + currentPage[2].split('.')[0];
        var urlLogo = path + '/assets/layouts/layout6/img/logo1.png';
        $('#logoVideoteca').attr('src', urlLogo);

		$(document).on('click','.pagination a', function(e){
			e.preventDefault();
			var url = $(this).attr('href');
			getVideos(url);
		});
	});

	function getVideos(url){
		$.ajax({
			url: url
		}).done(function(data){
			$('.table-responsive2').html(data);
			//console.log(data);
			
		}).fail(function (){
			alert('No se pudo leer la informacion');
		});
	}
		
	</script>
@endsection

resources/views/video/loadPreguntasTest.blade.php
                  <div class="table-scrollable">
                    
                    <table class="table table-striped table-hover">
                        <thead>
                          <tr>
                              <th> Pregunta </th>
                              <th> Respuestas</th>
                              <th></th>
                              <th></th>
                              <th></th>
                          </tr>
                        </thead>
                        <tbody>
                          @foreach($question as $item)
                            <tr data-id="{{ $item->idPregunta }}">
                                <td>{{ $item->Pregunta }} </td>
                                <td>
                                  <div class="form-group">
                                    <div class="col-md-6">
                                      <span>A) {{ $item->RespuestaA }}</span>
                                    </div>
                                  </div>
                                </td>
                                <td>
                                  <div class="form-group">
                                    <div class="col-md-6">
                                      <span>B) {{ $item->RespuestaB }}</span>
                                    </div>
                                  </div>
                                </td>
                                <td>
                                  <div class="form-group">
                                    <div class="col-md-6">
                                      <span>C) {{ $item->RespuestaC }}</span>
                                    </div>
                                  </div>
                                </td>
                                <td style="width:20px">
                                  <form id="form-{{ $item->idPregunta }}">
                                      @include('video.formRespuestaAlumno')
                                  </form>               
                                  <div class="response-Send-{{ $item->idPregunta }}">
                                  </div>
                                 </div>
                                </td>
                            </tr>
                          @endforeach
                        </tbody>
                    </table>
                  
                  </div>
                  <div class="form-group">
                  <!--PAGINADO DE LA TABLA -->
                    <table>
                      <thead>
                        <tr>
                          <th></th>
                          <th></th>
                        </tr>
                      </thead>
                      <tbody>

                        <tr>
                          <td>{{ $question->links() }}</td>
                          <td  align="right">{{ $question->firstItem() }} de {{ $question->count() }} en total {{ $question->total() }} preguntas</td>
                        </tr>

                      </tbody>
                    </table>
                <!-- TERMINO DEL PAGINADO -->
           
                    @if(Session::has('success'))
                        <div class="alert alert-success">
                            {{ Session::get('success') }}
                        </div>
                    @endif
                  </div>

resources/views/video/loadVideo.blade.php
@extends('layouts.master');

@section('title', 'BioVideoteca >> Videos')

@section('breadcrumbs')

@endsection

@section('content')

<div class="col-lg-8 col-xs-8 col-sm-10">
 <!-- BEGIN PORTLET-->
    <div class="portlet light bordered">
       <div class="portlet-title">
         <div class="caption">
            <span class="caption-subject font-dark bold uppercase">VIDEO</span>
            @if(Session::has('success'))
              <h4>{!! Session::get('success') !!}</h4>
            @endif
         </div>
        </div>
        <div class="portlet-body">
         
          <video id="videohtml5" class="vjs-tech" preload="auto" height="400" width="600" controls>
              <source src="{{ $linkVideo }}" type='video/mp4; codecs="avc1.42E01E, mp4a.40.2"' >
              <source src="{{ $linkVideo }}" type='video/ogg; codecs="theora, vorbis"' >
              Video no soportado. Descargalo <a href="{{ $linkVideo }}">aqui</a>
          </video>
         
          {!! Form::open(['route' => 'videoCalificacion.store']) !!}
             <div class="col-md-8">
                {{ Form::hidden('videoID', $detalleVideo->idVideo) }}
                {{ Form::select('cal_Video', $evaluarVideo, null, array('class' => 'form-control')) }}
              </div>
              <Button type ="submit">Calificar</Button>
          {!! Form::close() !!}
           </div>
         
    </div>

</div>

<div class="col-lg-4 col-xs-8 col-sm-10">
   <div class="portlet light bordered">
      <div class="portlet-title">
         <div class="caption">
            <span class="caption-subject font-dark bold uppercase">DESCRIPCION</span>
         </div>
      </div>
      {{ $detalleVideo->descripcion }}
      <br>
      <br>
      Nota: Algunos videos tienen cuestionarios, favor de responderlos.
  </div>
</div>
<div class="col-lg-12 col-xs-12 col-sm-12">

    <div class="portlet light bordered">
        <div class="portlet-title">
         <div class="caption">
            <i class="icon-share font-red-sunglo hide"></i>
            <span class="caption-subject font-dark bold uppercase">Cuestionario</span>
            <br>
            Instrucciones: Responde el siguiente cuestionario agregando la "letra" de la respuesta correcta.
         </div>
        </div>

        <div class="portlet-body">
               <h3>Cuestionario evaluado</h3>
        </div>
    </div>

@endsection

@section('page_script') 
  <script>
 $(document).ready(function(){

      //Actualiza el logo de la aplicacion de Videoteca
      var currentPage = window.location.href.split('/');
      var path = currentPage[0].split('.')[0] + '//' + currentPage[2].split('.')[0];
      var urlLogo = path + '/assets/layouts/layout6/img/logo1.png';
      $('#logoVideoteca').attr('src', urlLogo);
  });
</script>
@endsection

resources/views/video/viewIndex.blade.php
@if(Session::has('success'))
					    <div class="alert alert-success">
					        {{ Session::get('success') }}
					    </div>
					@endif
<table class="table table-striped table-bordered table-hover" id="tblVideo">
					<thead>
					<tr>
						<th>Nº</th>
						<th>Titulo</th>
						<th align="center">Descripcion</th>
						<th align="center">Duracion</th>
						<th align="center">Clasificacion</th>
					    @if(Auth::user()->role != 'alumno')
						<th align="center">Editar</th>
						@endif
						@if(Auth::user()->role === 'administrador')
					    <th>Eliminar</th>
					    @endif
					    <th>Ver</th>
					    @if(Auth::user()->role === 'administrador')
					    <th>Download</th>
					    @endif
					</tr>
				  </thead>
				  	<tbody>
				  	@foreach($videos as $item)
				  	<tr>
						<td>{{ $item->idVideo }}</td>
					   	<td>{{ $item->titulo }}</td>
					   	<td>{{ $item->descripcion }}</td>
					  	<td>{{ $item->duracion}}</td>
					  	<td>{{ $item->Nombre}}</td>
					  	@if(Auth::user()->role != 'alumno')
					   	<td>
					   		<a href="{{ route('videoCuestionario.show', $item->idVideo) }}" class="btn btn-warning"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></a>
					   	</td>
					   	@endif
					   	@if(Auth::user()->role === 'administrador')
					   	<td>
					   		<a href="{{ route('video.destroy', $item->idVideo) }}" class="btn btn-danger"><span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span></a>
					   	</td>
					   	@endif
					   	<td><a href="{{ route('video.show', $item->idVideo) }}" class="btn btn-primary"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span></a></td>
					   	@if(Auth::user()->role === 'administrador')
					   	<td><a href="{{ url('video/download', $item->idVideo) }}" class="btn btn-success"><span class="glyphicon glyphicon-save" aria-hidden="true"></span></a></td>
					   	@endif
					</tr>
					@endforeach
					</tbody>
				</table>
				<div class="form-group">
					<table>
						<thead>
							<tr>
								<th></th>
								<th></th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>{{ $videos->links() }}</td>
								<td  align="right">{{ $videos->firstItem() }} de {{ $videos->count() }} en total {{ $videos->total() }}</td>
							</tr>
						</tbody>
					</table>
					
</div>