app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
/*
Route::get('/', function () {
    return view('welcome');
});

Route::get('clasificacion_option', function(){
	
});

Route::resource('/pregunta', 'preguntaController');

Route::resource('video', 'videoController');

Route::resource('/cuestionario', 'cuestionarioController');


//Route::post('/clasificacionVideo/store','clasificacionVideoController@store')
Route::resource('/clasificacionVideo', 'clasificacionVideoController');

Route::post('/upload', function(){
     if(Input::hasFile('archivo')) {
          Input::file('archivo')
               ->move('carpetarArchivos','NuevoNombre');
     }
     return Redirect::back(('/');
});
*/
//Route::get('/registro', 'Auth\AuthController@getRegister');
//Route::post('/registro', 'Auth\AuthController@postRegister');

routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});



Auth::routes();

//Route::get('/', 'HomeController@index');

//Rutas del acceso a usuarios
Route::get('login', [
			'uses' => 'LoginController@login',
			'as' => 'login'
	]);
Route::post('login', 'LoginController@posLogin');
Route::get('logout', 'LoginController@getLogout');


//Rutas del registro a usuarios
Route::get('/registro', 'LoginController@getRegister');
Route::post('/registro', 'LoginController@create');

Route::resource('/video/download', 'videoController@download');

//Rutas de usuarios Tipo - Alumnos
Route::group( ['prefix' => 'alumno'] , function(){


	Route::get('/', function () {
   					 return view('UsuarioRol.alumno', ['Tipo_Acceso' => 'alumno']);
	});
	
	Route::resource('video', 'videoController');

	Route::resource('cuestionario', 'cuestionarioController');

	Route::resource('videoCalificacion', 'videoCalificacionController');

	Route::resource('preguntaRespuesta', 'preguntaRespuestaController');
	//Route::post('preguntaRespuesta', 'preguntaRespuestaController@store');

	Route::resource('usuarioTest', 'usuarioTestController');


});



//Rutas de usuario Tipo - Docente
Route::group( ['prefix' => 'docente'] , function(){

	Route::get('/', function () 
	{
		return view('UsuarioRol.docente', ['Tipo_Acceso' => 'docente']);
	});

	Route::resource('video', 'videoController');

	Route::resource('videoCuestionario', 'videoCuestionarioController');

	Route::resource('cuestionario', 'cuestionarioController');

	Route::resource('clasificacionVideo', 'clasificacionVideoController');
	
	Route::resource('pregunta', 'preguntaController');

	Route::resource('usuarioTest', 'usuarioTestController');

	Route::resource('preguntaRespuesta', 'preguntaRespuestaController');

});



//Rutas de usuario Tipo - Administrador
Route::group(['prefix' => 'administrador']  , function(){
//Route::group(['middleware' => 'administrador']  , function(){
	
	Route::get('/', function () 
	{
		return view('UsuarioRol.administrador');
	});

	Route::get('busquedaVideos', 'videoController@busquedaVideos');
	Route::resource('video', 'videoController');

	Route::resource('cuestionario', 'cuestionarioController');

	Route::resource('clasificacionVideo', 'clasificacionVideoController');

	Route::resource('pregunta', 'preguntaController');

	Route::resource('videoCuestionario', 'videoCuestionarioController');

	Route::resource('preguntaRespuesta', 'preguntaRespuestaController');

	Route::resource('usuarioTest', 'usuarioTestController');

	Route::resource('user', 'userController');
	
});

app/cuestionario.php
<?php

namespace Biobiblioteca;

use Illuminate\Database\Eloquent\Model;

class cuestionario extends Model
{
    //Configuracion de la tabla para almacenar los datos
	 protected $table = 'cuestionarios';

	 protected $fillable = ['Titulo', 'idClasificacion', 'Descripcion', 'activo'];

	 protected $primaryKey = 'idCuestionario';

   public $timestamps = true;



   public function scopeTitulo($query, $titulo = ""){

      	if(trim($titulo) != ""  ){
    		  $query->where('titulo', "like" , '%'.$titulo.'%');
       	}
        else{
          $query->orderBy('idCuestionario', 'asc');
        }
        return $query;
    }


    public function scopeStatus($query, $idStatus){

    	//dd('scope: '.$idStatus);
      if($idStatus === '1' || $idStatus === '0'){
    		$query->where('activo', $idStatus);
     	}
     
      return $query;
    }
}

app/Http/Controllers/cuestionarioController.php
<?php

namespace Biobiblioteca\Http\Controllers;

use Illuminate\Http\Request;
use Biobiblioteca\Http\Requests;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;
use Biobiblioteca\User;

use Biobiblioteca\video;
use Biobiblioteca\cuestionario;
use Biobiblioteca\clasificacionVideo;
use Biobiblioteca\cuestionarioVideo;


class cuestionarioController extends Controller
{
    protected $authRol;

    public function index(Request $request)
    {
            $cuestionarioAll = cuestionario::Titulo($request->get('titulo'))
                                            ->status($request->get('idStatus'))
                                            ->paginate(10);
            if($request->ajax() ){
               return view('cuestionario.loadCuestionarios', ['cuestionarios' => $cuestionarioAll ])->render(); 
            }

            return view('cuestionario.viewIndex', ['cuestionarios' => $cuestionarioAll ]);  
              
    }

    public function create()
    {
		$clasificaciones = clasificacionVideo::pluck('Nombre','idClasificacion');
        $videos = video::pluck('titulo','idVideo');
        
        return view('cuestionario.createIndex', [
		              'clasificaciones' => $clasificaciones,
                  'videolist' => $videos
		]);
        
    }

    public function store(Request $request)
    {

        if ($request['activo'] ===null) {
            // El usuario No marcó el checkbox 
            $valActivo = 0;
         } else {
           // El usuario Si marcó el chechbox
             $valActivo = 1;
         }


        $this->validate($request,[
                'titulo' => ['required', 'max:150'],
                'clasificaciones' => 'required',
                'videos' => 'required'
            ]);

    $findCuestionarioExistente = \DB::table('cuestionario_Video as cv')
                                    ->whereIn('cv.idVideo', [$request->videos] )
                                    ->value('idCuestionario');
      
    if($findCuestionarioExistente === null){
         $descripcionCampo = 'null';
        //Recuperar y Almacenar los valores en la base de datos
        $tableCuestionario = new cuestionario([
                    'Titulo' => Input::get('titulo'),
                    'idClasificacion' => Input::get('clasificaciones'),
                    'Descripcion' => $descripcionCampo,
                    'activo' => $valActivo
            ]);
        $tableCuestionario->save();
		
        //Recuperar el ultimo registro guardado y lo guardamos en la tabla relacion
        $RecuperarID = DB::table('cuestionarios')
                                         ->select('idCuestionario')
                                         ->orderBy('idCuestionario', 'DESC')
                                         ->first();

        $IDCuestionario = $RecuperarID->{'idCuestionario'};
     
        //Almacena los datos en la tabla relacion
        $tableRelacion = new cuestionarioVideo([
                     'idCuestionario' => $IDCuestionario,
                     'idVideo' =>  Input::get('videos')
            ]);
        $tableRelacion->save();

        //Recupera la informacion y la envia a la vista 
        $Rol = Auth::user()->role;
        return redirect()->to($Rol.'/cuestionario/');
    }else{

            return redirect()->back()->with('success', 'El cuestionario ya tiene un video asignado');

        }

    }

    public function show($idCuestionario)
    {
        //Busca al Cuestionario seleccionado
         $Find = cuestionario::find($idCuestionario);

         $clasificaciones = clasificacionVideo::pluck('Nombre','idClasificacion');
         $videos = video::pluck('titulo','idVideo');

        //Redirecciona al formulario de modificacion
        return view('cuestionario.editIndex', ['test' => $Find, 
                                              'clasificaciones' => $clasificaciones, 
                                              'videolist' => $videos
            ]);
       
    }

    public function edit()
    {
        
    }

    public function update(Request $request, $idCuestionario)
    {
        //Buscamos al registro que se va a eliminar
         $Find = cuestionario::find($idCuestionario);

         if ($request['activo'] ===null) {
            // El usuario No marcó el checkbox 
            $valActivo = 0;
         } else {
           // El usuario Si marcó el chechbox
             $valActivo = 1;
         }
       
        $this->validate($request,[
                'titulo'=> ['required', 'max:150'],
                'clasificaciones' => 'required'
        ]);

        $descripcionCampo = 'null';
        //Se recupera la informacion de la vista y se guarda
        $Find->Titulo = Input::get('titulo');
        $Find->idClasificacion = Input::get('clasificaciones');
        $Find->Descripcion = $descripcionCampo;
        $Find->activo = $valActivo;
        $Find->save();
        
        $Rol = Auth::user()->role;
        //Session::flash('success', 'Cuestionario Modificado ');
        return redirect()->to( $Rol.'/cuestionario' );

    }

    public function destroy($idCuestionario)
    {
        //Busca el registro y lo elimina
        $preguntaDelete = cuestionario::findOrFail($idCuestionario);

        $preguntaDelete-> delete();

        $FindVideo = cuestionarioVideo::find(Input::get('videos'));

        $FindVideo-> delete();

        /*
        return view('cuestionario.viewIndex', [
          'cuestionarios' =>  Cuestionario::all()
        ]);
        */
        Session::flash('success', 'Cuestionario Eliminado ');
        return redirect()->to('cuestionario/index');

    }
}

resources/views/cuestionario/addCuestionarioVideo.blade.php
@extends('layouts.master');

@section('title', 'BioVideoteca >> Video-Cuestionario')

@section('breadcrumbs')

@endsection

@section('content')
 
<!-- TABLA PARA FILTRAR CUESTIONARIOS -->
<div class="portlet-body">
 	<div class="table-responsive">
 	    <div class="portlet box purple">
	 	    <div class="portlet-title">
				<div class="caption">
	                <i class="fa fa-globe"></i>Listado de videos para agregar Cuestionarios 
				</div>
				<div class="tools"> </div>
	        </div>
	        <div class="portlet-body">
	        	<div class="panel-body">
					{!! Form::open(['route'=> 'video.index', 'method'=> 'GET', 'class'=> 'navbar-form navbar-left pull-right', 'role'=> 'search']) !!}
						<div class="form-group">
							{!! Form::text('titulo', null, ['class' => 'form-control', 'placeholder' => 'Buscar por Titulo' ]) !!}
							{!! Form::select('list_clasificacion', $clasificaciones, null, ['class' => 'form-control', 'placeholder' => 'seleccione']) !!}
						</div>
						<button type="submit" class="btn btn-default">Buscar</button>
					{!! Form::close() !!}
				</div>
				
				<table class="table table-striped table-bordered table-hover" id="tblVideo">
					<thead>
					<tr>
						<th>Nº</th>
						<th>Titulo</th>
						<th align="center">Descripcion</th>
						<th align="center">Duracion</th>
						<th align="center">Acciones</th>
					    
					</tr>
				  </thead>
				  	<tbody>
				  	@foreach($videos as $item)
				  	<tr>
						<td>{{ $item->idVideo }}</td>
						<td>{{ $item->titulo }}</td>
					   	<td>{{ $item->descripcion }}</td>
					  	<td>{{ $item->duracion}}</td>
					  	<td>
					   		<a href="{{ route('videoCuestionario.show', $item->idVideo) }}" class="btn btn-warning"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span></a>

					   	</td>
					   	
					</tr>
					@endforeach
					</tbody>
				</table>

				<div class="form-group">
					<table>
						<thead>
							<tr>
								<th></th>
								<th></th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>{{ $videos->links() }}</td>
								<td  align="right">{{ $videos->firstItem() }} de {{ $videos->count() }} en total {{ $videos->total() }}</td>
							</tr>
						</tbody>
					</table>
					 
				
				</div>
			</div>
		</div>
	</div>
</div>
<!-- FIN DE LA TABLA -->

@endsection

@section('page_script') 
   <script>
    $(document).ready(function(){
        //Actualiza el logo de la aplicacion de Videoteca
        var currentPage = window.location.href.split('/');
        var path = currentPage[0].split('.')[0] + '//' + currentPage[2].split('.')[0];
        var urlLogo = path + '/assets/layouts/layout6/img/logo1.png';
        $('#logoVideoteca').attr('src', urlLogo);

    });
</script>
@endsection

resources/views/cuestionario/createIndex.blade.php
@extends('layouts.master')
@section('title', 'BioVideoteca >> Creacion de Preguntas')

@section('breadcrumbs')

@endsection

@section('content')

<div class="portlet box blue">
  <div class="portlet-title">
  <div class="caption">
  	 Agregar un nuevo Cuestionario
  </div>
  </div>
</div>

<div class="portlet-body form">
     
<div class="form-body">
   <div class="form-horizontal">
@include('layout/partials/errors')
{!! Form::open(['route' => 'cuestionario.store']) !!}
     <div class="form-group">
	     <label class="col-md-3 control-label">Titulo del cuestionario</label> 
	     <div class="col-md-9" >
			    {{ Form::text('titulo', null,  ['class' => 'form-control']) }}
       </div>
      </div>

     <div class="form-group">
			<label class="col-md-3 control-label">Listado de videos</label>
			 <div class="col-md-9" >
			     {{ Form::select('videos', $videolist, null, array('class' => 'form-control')) }}
        </div>
	    </div>
     
      <div class="form-group">
	      <label class="col-md-3 control-label">Clasificacion del Cuestionario</label>
			  <div class="col-md-9" >
            	{{ Form::select('clasificaciones', $clasificaciones, null, array('class' => 'form-control')) }}
        </div>
		  </div>
       <!-- 
      <div class="form-group">
     
      <label class="col-md-3 control-label">Descripcion del Cuestionario</label>
        <div class="col-md-9">
	        {{ Form::textArea('descripcion', null,  ['class' => 'form-control']) }}
	      </div>
      </div>
      -->
      
      <div class="form-group">
          <label class="col-md-3 control-label">Activo </label> 
        <div class="col-md-9">
          {{ Form::checkbox('activo', 0, null, ['class' => 'field']) }}
        </div>
      </div>
      
      <div class="form-group">
        <div class="col-xs-12 col-md-12 form-group">
	         <button class="btn btn-primary pull-right" type="reset">Limpiar</button>
	         <button class="btn btn-primary pull-right" type="submit">Guardar</button>
        </div>
      </div>
      </div>
</div> 
{!! Form::close() !!}
</div>
@endsection                 

@section('page_script') 
   <script>
    $(document).ready(function(){
        //Actualiza el logo de la aplicacion de Videoteca
        var currentPage = window.location.href.split('/');
        var path = currentPage[0].split('.')[0] + '//' + currentPage[2].split('.')[0];
        var urlLogo = path + '/assets/layouts/layout6/img/logo1.png';
        $('#logoVideoteca').attr('src', urlLogo);

    });
</script>
@endsection

resources/views/cuestionario/editIndex.blade.php
@extends('layouts.master')
@section('title', 'BioVideoteca >> Edicion de Cuestionarios')

@section('breadcrumbs')

@endsection

@section('content')

<div class="portlet box blue">
  <div class="portlet-title">
  <div class="caption">
  	 Editar un Cuestionario
  </div>
  </div>
</div>

<div class="portlet-body form">
{{ Form::model($test, array('route' => array('cuestionario.update', $test->idCuestionario), 'method' => 'PUT')) }}
  <input type="hidden" name="_token" value="{{csrf_token() }}">
<div class="form-body">
  <div class="form-horizontal">

    <div class="form-group">
	    <label class="col-md-3 control-label">Titulo del cuestionario</label> 
	    <div class="col-md-9">
			     {{ Form::text('titulo', $test->Titulo, ['class' => 'form-control']) }}
      </div>
    </div>

    <div class="form-group">
			<label class="col-md-3 control-label">Listado de videos</label>
		  <div class="col-md-9">
			{{ Form::select('videos', $videolist, null, array('disabled' => 'disabled', 'class' => 'form-control')) }}
      </div>                    
	  </div>

    <div class="form-group">
	    <label class="col-md-3 control-label">Clasificacion del Video</label>
			<div class="col-md-9" >
         	{{ Form::select('clasificaciones', $clasificaciones, null, array('class' => 'form-control')) }}
      </div>
		</div>
    <!--
    <div class="form-group">
      <label class="col-md-3 control-label">Descripcion del Cuestionario </label>
      <div class="col-md-9">
         {{ Form::textarea('descripcion', $test->Descripcion, ['class' => 'form-control'] ) }}
	    </div>
    </div>
    -->
    <div class="form-group">
      <label class="col-md-3 control-label">Activo </label> 
      <div class="col-md-9">
         {{ Form::checkbox('activo', $test->activo, null, ['class' => 'field']) }}
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-9">
	    <button class="btn btn-primary pull-right" type="reset">Limpiar</button>
	    <button class="btn btn-primary pull-right" type="submit">Guardar</button>
      </div>
    </div>
  </div> 
</div>
{!! Form::close() !!}
</div>
@endsection                 

@section('page_script') 
   <script>
    $(document).ready(function(){
        //Actualiza el logo de la aplicacion de Videoteca
        var currentPage = window.location.href.split('/');
        var path = currentPage[0].split('.')[0] + '//' + currentPage[2].split('.')[0];
        var urlLogo = path + '/assets/layouts/layout6/img/logo1.png';
        $('#logoVideoteca').attr('src', urlLogo);

    });
</script>
@endsection

resources/views/cuestionario/loadCuestionarios.blade.php
<table class="table table-striped table-bordered table-hover" id="tblCuestionario">
    <thead>
	<tr>
	  <th>N°</th>
	  <th>Cuestionario</th>
	 <!-- <th align="center">Descripcion</th> -->
	  <th align="center"> Status </th>
    @if(Auth::user()->role != 'alumno')
	  <th align="center"> Editar </th>
	  <th></th>
    <th></th>
    @endif
	</tr>
  </thead>
  <tbody>
@foreach($cuestionarios as $cuestionario)
   <tr>
   <td>{{ $cuestionario->idCuestionario }}</td>
   <td>{{ $cuestionario->Titulo }}</td>
  <!-- <td>{{ $cuestionario->Descripcion }}</td>-->
   <td align="center">
   @if($cuestionario->activo == 1)
    activo
   @else
    inactivo
   @endif
   </td>
  @if(Auth::user()->role != 'alumno')
   <td align="center"> <a href="{{ route('cuestionario.show', $cuestionario->idCuestionario ) }}">  <span class="sub_icon glyphicon glyphicon-file">
   </td>
  <td align="center">
     {!! Form::open([
            'method' => 'DELETE',
            'route' => ['cuestionario.destroy', $cuestionario->idCuestionario]
       ]) !!}
       {!! Form::submit('Eliminar', ['class' => 'btn purple' ]) !!}
      {!! Form::close() !!} 
   </td>
   <td align="center">
     <a href="{{ route('pregunta.create', 'idCuestionario='.$cuestionario->idCuestionario ) }}" class="btn btn-sm green">Pregunta<i class="fa fa-plus"></i>
   </td>
   @endif
	</tr>
@endforeach
  </tbody>
  </table>
  <div class="form-group">
          <table>
            <thead>
              <tr>
                <th></th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>{{ $cuestionarios->links() }}</td>
                <td  align="right">{{ $cuestionarios->firstItem() }} de {{ $cuestionarios->count() }} en total {{ $cuestionarios->total() }}</td>
              </tr>
            </tbody>
          </table>
           
          @if(Session::has('success'))
              <div class="alert alert-success">
                  {{ Session::get('success') }}
              </div>
          @endif
  </div>

 </div>

resources/views/cuestionario/viewIndex.blade.php
@extends('layouts.master');

@section('title', 'BioVideoteca >> Creacion de Preguntas')

@section('breadcrumbs')

@endsection

@section('content')
	
<div class="portlet box blue">
  <div class="portlet-title">
    <div class="caption">
      <i class="fa fa-gift"></i>Listado de Cuestionarios
    </div>
  </div>

<div class="portlet-body">
    <div class="panel-body">
          {!! Form::open(['route'=> 'cuestionario.index', 'method'=> 'GET', 'class'=> 'navbar-form navbar-left pull-right', 'role'=> 'search']) !!}
            <div class="form-group">
              {!! Form::text('titulo', null, ['class' => 'form-control', 'placeholder' => 'Buscar por cuestionario' ]) !!}
              {!! Form::select('idStatus', array('2'=>'seleccione', '1' => 'Activo', '0' => 'inactivo'),  null, array('class' => 'form-control')) !!}
            </div>
            <button type="submit" class="btn btn-default">Buscar</button>
          {!! Form::close() !!}
    </div>
<div class="table-responsive">

  @if($cuestionarios->count())
    @include('cuestionario.loadCuestionarios')
  @else
    <h2>No se encontraron cuestionarios registrados</h2>
  @endif
</div>
  @endsection

@section('page_script') 
  <script>
  $(document).ready(function(){
    
    //Actualiza el logo de la aplicacion de Videoteca
    var currentPage = window.location.href.split('/');
    var path = currentPage[0].split('.')[0] + '//' + currentPage[2].split('.')[0];
    var urlLogo = path + '/assets/layouts/layout6/img/logo1.png';
    $('#logoVideoteca').attr('src', urlLogo);


    $(document).on('click','.pagination a', function(e){
      e.preventDefault();
      var url = $(this).attr('href');
      getCuestionarios(url);
    });
  });

  function getCuestionarios(url){

    $.ajax({
      url: url
    }).done(function(data){
      $('.table-responsive').html(data);
      //console.log(data);
      
    }).fail(function (){
      alert('No se pudo leer la informacion');
    });

  }
    
  </script>
@endsection