app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
/*
Route::get('/', function () {
    return view('welcome');
});

Route::get('clasificacion_option', function(){
	
});

Route::resource('/pregunta', 'preguntaController');

Route::resource('video', 'videoController');

Route::resource('/cuestionario', 'cuestionarioController');


//Route::post('/clasificacionVideo/store','clasificacionVideoController@store')
Route::resource('/clasificacionVideo', 'clasificacionVideoController');

Route::post('/upload', function(){
     if(Input::hasFile('archivo')) {
          Input::file('archivo')
               ->move('carpetarArchivos','NuevoNombre');
     }
     return Redirect::back(('/');
});
*/
//Route::get('/registro', 'Auth\AuthController@getRegister');
//Route::post('/registro', 'Auth\AuthController@postRegister');

routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});



Auth::routes();

//Route::get('/', 'HomeController@index');

//Rutas del acceso a usuarios
Route::get('login', [
			'uses' => 'LoginController@login',
			'as' => 'login'
	]);
Route::post('login', 'LoginController@posLogin');
Route::get('logout', 'LoginController@getLogout');


//Rutas del registro a usuarios
Route::get('/registro', 'LoginController@getRegister');
Route::post('/registro', 'LoginController@create');

Route::resource('/video/download', 'videoController@download');

//Rutas de usuarios Tipo - Alumnos
Route::group( ['prefix' => 'alumno'] , function(){


	Route::get('/', function () {
   					 return view('UsuarioRol.alumno', ['Tipo_Acceso' => 'alumno']);
	});
	
	Route::resource('video', 'videoController');

	Route::resource('cuestionario', 'cuestionarioController');

	Route::resource('videoCalificacion', 'videoCalificacionController');

	Route::resource('preguntaRespuesta', 'preguntaRespuestaController');
	//Route::post('preguntaRespuesta', 'preguntaRespuestaController@store');

	Route::resource('usuarioTest', 'usuarioTestController');


});



//Rutas de usuario Tipo - Docente
Route::group( ['prefix' => 'docente'] , function(){

	Route::get('/', function () 
	{
		return view('UsuarioRol.docente', ['Tipo_Acceso' => 'docente']);
	});

	Route::resource('video', 'videoController');

	Route::resource('videoCuestionario', 'videoCuestionarioController');

	Route::resource('cuestionario', 'cuestionarioController');

	Route::resource('clasificacionVideo', 'clasificacionVideoController');
	
	Route::resource('pregunta', 'preguntaController');

	Route::resource('usuarioTest', 'usuarioTestController');

	Route::resource('preguntaRespuesta', 'preguntaRespuestaController');

});



//Rutas de usuario Tipo - Administrador
Route::group(['prefix' => 'administrador']  , function(){
//Route::group(['middleware' => 'administrador']  , function(){
	
	Route::get('/', function () 
	{
		return view('UsuarioRol.administrador');
	});

	Route::get('busquedaVideos', 'videoController@busquedaVideos');
	Route::resource('video', 'videoController');

	Route::resource('cuestionario', 'cuestionarioController');

	Route::resource('clasificacionVideo', 'clasificacionVideoController');

	Route::resource('pregunta', 'preguntaController');

	Route::resource('videoCuestionario', 'videoCuestionarioController');

	Route::resource('preguntaRespuesta', 'preguntaRespuestaController');

	Route::resource('usuarioTest', 'usuarioTestController');

	Route::resource('user', 'userController');
	
});

resources/views/layouts/partials/foot.blade.php
        <!--[if lt IE 9]>
<script src="/assets/global/plugins/respond.min.js"></script>
<script src="/assets/global/plugins/excanvas.min.js"></script>
<script src="/assets/global/plugins/ie8.fix.min.js"></script>
<![endif]-->
        <!-- BEGIN CORE PLUGINS -->
        <script src="/assets/global/plugins/jquery.min.js" type="text/javascript"></script>
        <script src="/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="/assets/global/plugins/js.cookie.min.js" type="text/javascript"></script>
        <script src="/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
        <script src="/assets/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
        <script src="/assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
        <!-- END CORE PLUGINS -->
        <!-- BEGIN THEME GLOBAL SCRIPTS -->
        <script src="/assets/global/scripts/app.min.js" type="text/javascript"></script>
        <!-- END THEME GLOBAL SCRIPTS -->
        <!-- BEGIN THEME LAYOUT SCRIPTS -->
        <script src="/assets/layouts/layout6/scripts/layout.min.js" type="text/javascript"></script>
        <script src="/assets/layouts/global/scripts/quick-sidebar.min.js" type="text/javascript"></script>
        <script src="/assets/layouts/global/scripts/quick-nav.min.js" type="text/javascript"></script>
        <!-- END THEME LAYOUT SCRIPTS -->

resources/views/layouts/partials/head.blade.php
    <head>
        <meta charset="utf-8" />
        <title>@yield('title')</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta content="#1 selling multi-purpose bootstrap admin theme sold in themeforest marketplace packed with angularjs, material design, rtl support with over thausands of templates and ui elements and plugins to power any type of web applications including saas and admin dashboards. Preview page of Theme #6 for blank page layout"
            name="description" />
        <meta content="" name="author" />
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <!-- BEGIN LAYOUT FIRST STYLES -->
        <link href="//fonts.googleapis.com/css?family=Oswald:400,300,700" rel="stylesheet" type="text/css" />
        <!-- END LAYOUT FIRST STYLES -->
        <!-- BEGIN GLOBAL MANDATORY STYLES -->
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
        
        <link href="/assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
        <link href="/assets/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css" />
        <link href="/assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link href="/assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet" type="text/css" />
        <!-- END GLOBAL MANDATORY STYLES -->
        <!-- BEGIN THEME GLOBAL STYLES -->
        <link href="/assets/global/css/components-rounded.min.css" rel="stylesheet" id="style_components" type="text/css" />
        <link href="/assets/global/css/plugins.min.css" rel="stylesheet" type="text/css" />
        <!-- END THEME GLOBAL STYLES -->
        <!-- BEGIN THEME LAYOUT STYLES -->
        <link href="/assets/layouts/layout6/css/layout.min.css" rel="stylesheet" type="text/css" />
        <link href="/assets/layouts/layout6/css/custom.min.css" rel="stylesheet" type="text/css" />
        <!-- END THEME LAYOUT STYLES -->
        <link rel="shortcut icon" href="favicon.ico" /> </head>

resources/views/layouts/partials/header.blade.php
        <!-- BEGIN HEADER -->
        <header class="page-header">
            <nav class="navbar" role="navigation">
                <div class="container-fluid">
                    <div class="havbar-header">
                        <!-- BEGIN LOGO -->
                         @if (Auth::guest()) 
                        <a id="index" class="navbar-brand" href="/index.php"> <h1><span class="font-yellow-crusta" >VIDEOTECA DE BIOMEDICA y GASTROENTEROLOGIA, UANL</h1>
                        </a>
                        @else
                        <a id="index" class="navbar-brand" href="/index.php/{{ Auth::user()->role }}"> <h1><span class="font-yellow-crusta" >VIDEOTECA DE BIOMEDICA y GASTROENTEROLOGIA, UANL</h1>
                        </a>
                        @endif
                        <!-- END LOGO -->
                        <!-- BEGIN TOPBAR ACTIONS -->
                        <div class="topbar-actions">

                            <!-- BEGIN HEADER SEARCH BOX -->
                         @if (Auth::guest())   
                            <div class="btn-group-notification btn-group" id="header_notification_bar">
                                <button type="button" class="btn md-skip dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                                  </button>
                                <ul class="dropdown-menu-v2">
                                    <li class="external">
                                        <h3>
                                        <span class="bold">12 pending</span> notifications</h3>
                                    </li>
                        
                                    <li>
                                        <ul class="dropdown-menu-list scroller" style="height: 250px; padding: 0;" data-handle-color="#637283">
                                            <li>
                                                <a href="/index.php/registro">
                                                    <span class="details">
                                                        <span class="label label-sm label-icon label-success md-skip">
                                                            <i class="fa fa-plus"></i>
                                                        </span> Registrarse </span>
                                                </a>
                                            </li>
                                            <li>
                                                 <a href="/index.php/login">
                                                <i class="icon-key"></i> Iniciar sesion </a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                            <!-- END GROUP NOTIFICATION -->

                            <!-- BEGIN USER AUTHENTICATION -->
                        @else 
                            <label class="font-yellow-crusta"><h2>{{ Auth::user()->name }}</h2></label>
                            <div class="btn-group-img btn-group">
                                <button type="button" class="btn btn-sm dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                                 <!-- <img src="../assets/layouts/layout6/img/avatar1.jpg" alt=""> -->
                                </button>
                                <ul class="dropdown-menu-v2" role="menu">
                                    <li class="divider"> </li>
                                 
                                   <li>
                                        <a href="/index.php/logout">
                                            <i class="icon-lock"></i> Cerrar Sesion </a>
                                    </li>
                               
                                </ul>
                            </div>
                        @endif
                            <!-- END USER PROFILE -->
                        </div>
                        <!-- END TOPBAR ACTIONS -->
                    </div>
                </div>
                <!--/container-->
            </nav>
        </header>
        <!-- END HEADER -->

resources/views/layouts/partials/sidebar.blade.php
                <div class="page-sidebar-wrapper">
                    <!-- BEGIN SIDEBAR -->
                    <div class="page-sidebar navbar-collapse collapse">
                        <!-- BEGIN SIDEBAR MENU -->
                        <ul class="page-sidebar-menu  page-header-fixed " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
                            <li class="nav-item start ">
                            </script>
                            <img src="../assets/layouts/layout6/img/logo1.png" id="logoVideoteca"> 
                            <a href="/index.php/{{ Auth::user()->role }}" class="nav-link nav-toggle">
                                <span class="title">Menù principal</span>
                                <h2 class="uppercase" >{{ Auth::user()->role }} </h2>
                            </a>
                            </li>
                            <li class="heading">
                                <h3 class="uppercase">Operaciones</h3>
                            </li>
                            <li class="nav-item  ">
                                <a href="javascript:;" class="nav-link nav-toggle">
                                    <i class="icon-film"></i>
                                    <span class="title">Video</span>
                                    <span class="arrow"></span>
                                </a>
                                <ul class="sub-menu">
                                    <li class="nav-item  ">
                                        <a href="{{ route('video.create', []) }}" class="nav-link ">
                                            <span class="title">Agregar</span>
                                        </a>
                                    </li>
                                    <li class="nav-item  ">
                                        <a href="{{ route('video.index', []) }}" class="nav-link ">
                                            <span class="title">Examinar</span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li class="nav-item  ">
                                <a href="javascript:;" class="nav-link nav-toggle">
                                    <i class="icon-notebook"></i>
                                    <span class="title">Cuestionario</span>
                                    <span class="arrow"></span>
                                </a>
                                <ul class="sub-menu">
                                    <li class="nav-item  ">
                                        <a href="{{ route('cuestionario.create', []) }}" class="nav-link ">
                                            <span class="title">Agregar</span>
                                        </a>
                                    </li>
                                    <li class="nav-item  ">
                                        <a href="{{ route('cuestionario.index', []) }}" class="nav-link ">
                                            <span class="title">Examinar</span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li class="nav-item  ">
                                <a href="javascript:;" class="nav-link nav-toggle">
                                    <i class="icon-note"></i>
                                    <span class="title">Preguntas</span>
                                    <span class="arrow"></span>
                                </a>
                                <ul class="sub-menu">
                                    <li class="nav-item  ">
                                        <a href="{{ route('pregunta.index', []) }}" class="nav-link ">
                                            <span class="title">Examinar</span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li class="nav-item  ">
                                <a href="javascript:;" class="nav-link nav-toggle">
                                    <i class="icon-layers"></i>
                                    <span class="title">Clasificaciones</span>
                                    <span class="arrow"></span>
                                </a>
                                <ul class="sub-menu">
                                    <li class="nav-item  ">
                                        <a href="{{ route('clasificacionVideo.create', []) }}" class="nav-link ">
                                            <span class="title">Agregar</span>
                                        </a>
                                    </li>
                                    <li class="nav-item  ">
                                        <a href="{{ route('clasificacionVideo.index', []) }}" class="nav-link ">
                                            <span class="title">Examinar</span>
                                        </a>
                                    </li>
                                </ul>
                            </li>

                            <li class="heading">
                                <h3 class="uppercase">Reportes</h3>
                            </li>
                            <li class="nav-item  ">
                                <a href="javascript:;" class="nav-link ">
                                     <i class="icon-docs"></i>
                                    <span class="title">Videos mas visitados</span>
                                     <span class="arrow"></span>
                                </a>
                                <ul class="sub-menu">
                                    <li class="nav-item  ">
                                        <a href="{{ route('videoCalificacion.index', []) }}" class="nav-link ">
                                            <span class="title">Examinar</span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li class="jnav-item  ">
                                <a href="javascript:;" class="nav-link ">
                                    <i class="icon-docs"></i>
                                    <span class="title">Usuarios destacados</span>
                                    <span class="arrow"></span>
                                </a>
                                <ul class="sub-menu">
                                    <li class="nav-item  ">
                                        <a href="{{ route('usuarioTest.index', []) }}" class="nav-link ">
                                            <span class="title">Examinar</span>
                                        </a>
                                    </li>
                                    <li class="nav-item  ">
                                        <a href="{{ route('user.index', []) }}" class="nav-link ">
                                            <span class="title">Usuarios Registrados</span>
                                        </a>
                                    </li>
                                </ul>
                            </li>

                        </ul>
                        <!-- END SIDEBAR MENU -->
                    </div>
                    <!-- END SIDEBAR -->
                </div>

resources/views/layouts/partials/sidebar_alumno.blade.php
<div class="page-sidebar-wrapper">
                    <!-- BEGIN SIDEBAR -->
                    <div class="page-sidebar navbar-collapse collapse">
                        <ul class="page-sidebar-menu  page-header-fixed " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
                            <li class="nav-item start ">
                                <img src="../assets/layouts/layout6/img/logo1.png" id="logoVideoteca"> 
                                <a href="/index.php/{{ Auth::user()->role }}" class="nav-link nav-toggle">
                                    <span class="title">Menu principal</span>
                                     <h2 class="uppercase" align="center">{{ Auth::user()->role }} </h2>
                                </a>
                             </li>
                           <li class="heading">
                                <h3 class="uppercase">Operaciones</h3>
                            </li>
                            <li class="nav-item  ">
                                <a href="javascript:;" class="nav-link nav-toggle">
                                    <i class="icon-camcorder"></i>
                                    <span class="title">Video</span>
                                    <span class="arrow"></span>
                                </a>
                                <ul class="sub-menu">
                                     <li class="nav-item  ">
                                        <a href="{{ url('alumno/video') }}" class="nav-link ">
                                            <span class="title">Examinar</span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li class="nav-item  ">
                                <a href="javascript:;" class="nav-link nav-toggle">
                                    <i class="icon-docs"></i>
                                    <span class="title">Cuestionario</span>
                                    <span class="arrow"></span>
                                </a>
                                <ul class="sub-menu">
                                    <li class="nav-item  ">
                                        <a href="{{ url('alumno/cuestionario/' ) }}" class="nav-link ">
                                            <span class="title">Examinar</span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                        <!-- END SIDEBAR MENU -->
                    </div>
                    <!-- END SIDEBAR -->
</div>

resources/views/layouts/partials/sidebar_docente.blade.php
<div class="page-sidebar-wrapper">
                    <!-- BEGIN SIDEBAR -->
                    <div class="page-sidebar navbar-collapse collapse">
                       
                        <ul class="page-sidebar-menu  page-header-fixed " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
                            <li class="nav-item start ">
                                <img src="../assets/layouts/layout6/img/logo1.png" align="vertical-align: middle;" id="logoVideoteca"> 
                                <a href="/index.php/{{ Auth::user()->role }}" class="nav-link nav-toggle">
                                    <span class="title">Menu principal</span>
                                    <h2 class="uppercase" align="center">{{ Auth::user()->role }} </h2>
                                </a>
                             </li>
                            
                            <li class="heading">
                                <h3 class="uppercase">Operaciones</h3>
                            </li>
                            <li class="nav-item  ">
                                <a href="javascript:;" class="nav-link nav-toggle">
                                    <i class="icon-camcorder"></i>
                                    <span class="title">Video</span>
                                    <span class="arrow"></span>
                                </a>
                                <ul class="sub-menu">
                                    <li class="nav-item  ">
                                        <a href="{{ route('video.create', []) }}" class="nav-link ">
                                            <span class="title">Agregar</span>
                                        </a>
                                    </li>
                                    <li class="nav-item  ">
                                        <a href="{{ url('docente/video') }}" class="nav-link ">
                                            <span class="title">Examinar</span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li class="nav-item  ">
                                <a href="javascript:;" class="nav-link nav-toggle">
                                    <i class="icon-docs"></i>
                                    <span class="title">Cuestionario</span>
                                    <span class="arrow"></span>
                                </a>
                                <ul class="sub-menu">
                                    <li class="nav-item  ">
                                        <a href="{{ url('docente/cuestionario/create') }}" class="nav-link ">
                                            <span class="title">Agregar</span>
                                        </a>
                                    </li>
                                    <li class="nav-item  ">
                                        <a href="{{ url('docente/cuestionario') }}" class="nav-link ">
                                            <span class="title">Examinar</span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li class="nav-item  ">
                                <a href="javascript:;" class="nav-link nav-toggle">
                                    <i class="icon-note"></i>
                                    <span class="title">Pregunta</span>
                                    <span class="arrow"></span>
                                </a>
                                <ul class="sub-menu">
                                    <li class="nav-item  ">
                                        <a href="{{ url('docente/pregunta' ) }}" class="nav-link ">
                                            <span class="title">Examinar</span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a href="layout_blank_page.html" class="nav-link ">
                                    <i class="icon-layers"></i>
                                    <span class="title">Clasificaciones</span>
                                    <span class="arrow"></span>
                                </a>
                                <ul class="sub-menu">
                                    <li class="nav-item  ">
                                        <a href="{{ route('clasificacionVideo.create', 'docente') }}" class="nav-link ">
                                            <span class="title">Agregar</span>
                                        </a>
                                    </li>
                                    <li class="nav-item  ">
                                        <a href="{{ route('clasificacionVideo.index', 'docente') }}" class="nav-link ">
                                            <span class="title">Examinar</span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                        <!-- END SIDEBAR MENU -->
                    </div>
                    <!-- END SIDEBAR -->
</div>