app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
/*
Route::get('/', function () {
    return view('welcome');
});

Route::get('clasificacion_option', function(){
	
});

Route::resource('/pregunta', 'preguntaController');

Route::resource('video', 'videoController');

Route::resource('/cuestionario', 'cuestionarioController');


//Route::post('/clasificacionVideo/store','clasificacionVideoController@store')
Route::resource('/clasificacionVideo', 'clasificacionVideoController');

Route::post('/upload', function(){
     if(Input::hasFile('archivo')) {
          Input::file('archivo')
               ->move('carpetarArchivos','NuevoNombre');
     }
     return Redirect::back(('/');
});
*/
//Route::get('/registro', 'Auth\AuthController@getRegister');
//Route::post('/registro', 'Auth\AuthController@postRegister');

routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});



Auth::routes();

//Route::get('/', 'HomeController@index');

//Rutas del acceso a usuarios
Route::get('login', [
			'uses' => 'LoginController@login',
			'as' => 'login'
	]);
Route::post('login', 'LoginController@posLogin');
Route::get('logout', 'LoginController@getLogout');


//Rutas del registro a usuarios
Route::get('/registro', 'LoginController@getRegister');
Route::post('/registro', 'LoginController@create');

Route::resource('/video/download', 'videoController@download');

//Rutas de usuarios Tipo - Alumnos
Route::group( ['prefix' => 'alumno'] , function(){


	Route::get('/', function () {
   					 return view('UsuarioRol.alumno', ['Tipo_Acceso' => 'alumno']);
	});
	
	Route::resource('video', 'videoController');

	Route::resource('cuestionario', 'cuestionarioController');

	Route::resource('videoCalificacion', 'videoCalificacionController');

	Route::resource('preguntaRespuesta', 'preguntaRespuestaController');
	//Route::post('preguntaRespuesta', 'preguntaRespuestaController@store');

	Route::resource('usuarioTest', 'usuarioTestController');


});



//Rutas de usuario Tipo - Docente
Route::group( ['prefix' => 'docente'] , function(){

	Route::get('/', function () 
	{
		return view('UsuarioRol.docente', ['Tipo_Acceso' => 'docente']);
	});

	Route::resource('video', 'videoController');

	Route::resource('videoCuestionario', 'videoCuestionarioController');

	Route::resource('cuestionario', 'cuestionarioController');

	Route::resource('clasificacionVideo', 'clasificacionVideoController');
	
	Route::resource('pregunta', 'preguntaController');

	Route::resource('usuarioTest', 'usuarioTestController');

	Route::resource('preguntaRespuesta', 'preguntaRespuestaController');

});



//Rutas de usuario Tipo - Administrador
Route::group(['prefix' => 'administrador']  , function(){
//Route::group(['middleware' => 'administrador']  , function(){
	
	Route::get('/', function () 
	{
		return view('UsuarioRol.administrador');
	});

	Route::get('busquedaVideos', 'videoController@busquedaVideos');
	Route::resource('video', 'videoController');

	Route::resource('cuestionario', 'cuestionarioController');

	Route::resource('clasificacionVideo', 'clasificacionVideoController');

	Route::resource('pregunta', 'preguntaController');

	Route::resource('videoCuestionario', 'videoCuestionarioController');

	Route::resource('preguntaRespuesta', 'preguntaRespuestaController');

	Route::resource('usuarioTest', 'usuarioTestController');

	Route::resource('user', 'userController');
	
});

app/Pregunta.php
<?php

namespace Biobiblioteca;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Pregunta extends Model
{
   
     //Tabla que se va asociar al modelo
	 protected $table = 'preguntas';

     protected $fillable = ['Pregunta', 'RespuestaA','RespuestaB','RespuestaC','Resp_Correcta', 'solucion'];

     protected $primaryKey = 'idPregunta';

     public $timestamps = true;

     public function scopeCuestionario($query, $titulo = ""){

    	//dd('scope: '.$titulo);
      	if(trim($titulo) != ""  ){
    		$query= DB::table('cuestionario_pregunta')
                ->join('preguntas', 'preguntas.idPregunta', '=', 'cuestionario_pregunta.idPregunta')
                ->join('cuestionarios', 'cuestionarios.idCuestionario', '=', 'cuestionario_pregunta.idCuestionario')
                ->select('cuestionario_pregunta.idPregunta','cuestionario_pregunta.idCuestionario','cuestionarios.Titulo','preguntas.Pregunta','preguntas.Resp_Correcta')
                ->where('cuestionarios.titulo', "like" , '%'.$titulo.'%')
                ->orderBy('cuestionario_pregunta.idCuestionario', 'ASC');
     	}else
        {
            $query= DB::table('cuestionario_pregunta')
                ->join('preguntas', 'preguntas.idPregunta', '=', 'cuestionario_pregunta.idPregunta')
                ->join('cuestionarios', 'cuestionarios.idCuestionario', '=', 'cuestionario_pregunta.idCuestionario')
                ->select('cuestionario_pregunta.idPregunta','cuestionario_pregunta.idCuestionario','cuestionarios.Titulo','preguntas.Pregunta','preguntas.Resp_Correcta')
                ->orderBy('cuestionario_pregunta.idCuestionario', 'ASC');
               
        }

        return $query;
    }
}

app/Http/Controllers/preguntaController.php
<?php

namespace Biobiblioteca\Http\Controllers;

use Illuminate\Http\Request;

use Biobiblioteca\Http\Requests;
use Biobiblioteca\Pregunta;
use Biobiblioteca\video;
use Biobiblioteca\cuestionariopregunta;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\DB;

class preguntaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request) 
    {
        //dd($request);
        $listaPreguntas = Pregunta::cuestionario($request->get('titulo'))->paginate(10);
       
        if($request->ajax() ){
            return view('pregunta.loadPregunta',['preguntas' => $listaPreguntas])->render();    
        }

        return view('pregunta.viewIndex', ['preguntas' => $listaPreguntas]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      $input = Input::all();
      $idCuestionario = $input['idCuestionario'];
      //return view('pregunta.createIndex', ['new' => true, 'preguntas' => new Pregunta, 'CuestionarioID' => $idCuestionario]);
      return view('pregunta.createIndex', ['CuestionarioID' => $idCuestionario]);
          
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //Validar Datos
        $this->validate($request,[
			'pregunta'=> 'required',
			'respuestaA' => 'required',
			'respuestaB' => 'required',
			'respuestaC' => 'required',
			'respuestaCorrecta' => ['required', 'max:1'],
            'solucion' => 'required'
		]);

        //Recuperar los valores del formulario
        //Modelo que recopila la informacion que sera enviada la base de datos      
        $entry = new Pregunta([
	      'Pregunta' => Input::get('pregunta'),
	      'RespuestaA' => Input::get('respuestaA'),
	      'RespuestaB' => Input::get('respuestaB'),
	      'RespuestaC' => Input::get('respuestaC'),
	      'Resp_Correcta' => Input::get('respuestaCorrecta'),
          'solucion' => Input::get('solucion')
        ]);
        $entry->save();

        //Recuperar el ultimo registro guardado y lo guardamos en la tabla relacion
        $RecuperarID = DB::table('preguntas')
                                ->select('idPregunta')
                                ->orderBy('idPregunta', 'DESC')
                                ->first();

        $idPregunta = $RecuperarID ->{'idPregunta'};

        $entryRelacion = new cuestionariopregunta([
                        'idCuestionario' => Input::get('Cuestionario_ID'),
                        'idPregunta' => $idPregunta
        ]);
        $entryRelacion-> save();

        //Envia al listado de preguntas para ver todas las preguntas
        Session::flash('flash_message', 'Pregunta Agregada!!');
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($idPregunta)
    {
        $preguntaFind = Pregunta::find($idPregunta);
        
        return view('pregunta.editIndex', ['question' => $preguntaFind] ); 
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($idPregunta)
    {
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update( $idPregunta , Request $request)
    {
         //Busca y edita la pregunta
         $preguntaFind = Pregunta::find($idPregunta);
         
         $this->validate($request,[
                'pregunta'=> 'required',
                'respuestaA' => 'required',
                'respuestaB' => 'required',
                'respuestaC' => 'required',
                'respuestaCorrecta' => ['required', 'max:1']
                ]);

         //Guardar la informacion 
         $preguntaFind->Pregunta = Input::get('pregunta');
         $preguntaFind->RespuestaA = Input::get('respuestaA');
         $preguntaFind->RespuestaB = Input::get('respuestaB');
         $preguntaFind->RespuestaC = Input::get('respuestaC');
         $preguntaFind->Resp_Correcta = Input::get('respuestaCorrecta');
         $preguntaFind->solucion = Input::get('solucion');
         $preguntaFind->save();

         //Retorna al listado de vista de las preguntas
         //return view('pregunta.viewIndex', ['preguntas' => Pregunta::all() ]);
         $Rol = \Auth::user()->role;
         return redirect()->to($Rol.'/pregunta');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($idPregunta)
    {
        //Busca el registro y lo elimina
        Pregunta::destroy($idPregunta);

        return view('pregunta.viewIndex', [
          'preguntas' => Pregunta::all()
        ]);
    }
}

resources/views/pregunta/createIndex.blade.php
@extends('layouts.master')
@section('title', 'BioVideoteca >> Creaciòn de Preguntas')

@section('breadcrumbs')

@endsections

@section('content')

<div class="portlet box blue">
  <div class="portlet-title">
    <div class="caption">
      <i class="fa fa-gift"></i>
        Agregar una nueva pregunta al cuestionario
      </div>
  </div>

@if(Session::has('flash_message'))
    <div class="alert alert-success">
        {{ Session::get('flash_message') }}
    </div>
@endif

<div class="portlet-body form">
  <div class="form-body"> 
  <div class="form-horizontal">
    @include('layout/partials/errors')
{!! Form::open(['route' => 'pregunta.store']) !!}
  <input type="hidden" name="_token" value="{{csrf_token() }}">
   {{ Form::hidden('Cuestionario_ID', $CuestionarioID) }}
       <div class="form-group">
          <label class="col-md-3 control-label">Pregunta   </label>
          <div class="col-md-9" >
            {{ Form::text('pregunta', null, ['class' => 'form-control']) }}
          </div>
       </div>

       <div class="form-group">
          <label class="col-md-3 control-label">RespuestaA:</label>
          <div class="col-md-9"" >
             {{ Form::text('respuestaA',  null, ['class' => 'form-control']) }} 
          </div >
       </div>

       <div class="form-group">
          <label class="col-md-3 control-label">RespuestaB:</label>
          <div class="col-md-9" >
             {{ Form::text('respuestaB',  null, ['class' => 'form-control']) }}
          </div>
       </div>
       
       <div class="form-group">
          <label class="col-md-3 control-label">RespuestaC:</label>
          <div class="col-md-9" >
            {{ Form::text('respuestaC',  null, ['class' => 'form-control']) }}
          </div>
        </div>

       <div class="form-group">
          <label class="col-md-3 control-label">Introduzca la letra de la respuesta correcta:</label>
          <div class="col-md-9" >
          {{ Form::text('respuestaCorrecta', null, ['class' => 'form-control']) }}
           </div>
       </div>       

       <div class="form-group">
          <label class="col-md-3 control-label">Explique el motivo de la respuesta:</label>
          <div class="col-md-9" >
          {{ Form::text('solucion', null, ['class' => 'form-control']) }}
           </div>
       </div>
       <div class="form-group">
            {{ Form::submit('Guardar Pregunta',array('class'=>'btn purple')) }}
            {{ Form::reset('Limpiar',array('class'=>'btn btn-success')) }}
       </div>
    </div>
  </div> 
    {!! Form::close() !!}
    <!-- </form> -->
</div>
@endsection

@section('page_script') 
   <script>
    $(document).ready(function(){
        //Actualiza el logo de la aplicacion de Videoteca
        var currentPage = window.location.href.split('/');
        var path = currentPage[0].split('.')[0] + '//' + currentPage[2].split('.')[0];
        var urlLogo = path + '/assets/layouts/layout6/img/logo1.png';
        $('#logoVideoteca').attr('src', urlLogo);

    });
</script>
@endsection

resources/views/pregunta/editIndex.blade.php
@extends('layouts.master')
@section('title', 'BioVideoteca >> Modificar la Pregunta')

@section('breadcrumbs')

@endsections

@section('content')

<div class="portlet box blue">
  <div class="portlet-title">
    <div class="caption">
      <i class="fa fa-gift"></i>
        Editar una pregunta
      </div>
  </div>

<div class="portlet-body form">
  <div class="form-body">
    <div class="form-horizontal"> 
    @include('layout/partials/errors')
{{ Form::model($question, array('route' => array('pregunta.update', $question->idPregunta), 'method' => 'PUT')) }}
  <input type="hidden" name="_token" value="{{csrf_token() }}">

      <div class="form-group">
          <label class="col-md-3 control-label">Pregunta:</label>
          <div class="col-md-9" >
            {{ Form::text('pregunta', $question->Pregunta, ['class' => 'form-control']) }} 
          </div>
      </div>

      <div class="form-group">
          <label class="col-md-3 control-label">RespuestaA:</label>
          <div class="col-md-9" >
            {{ Form::text('respuestaA', $question->RespuestaA,  ['class' => 'form-control'] ) }}
          </div class="input-group">
      </div>

      <div class="form-group">
          <label class="col-md-3 control-label">RespuestaB:</label>
          <div class="col-md-9" >
            {{ Form::text('respuestaB', $question->RespuestaB,  ['class' => 'form-control'] ) }} 
          </div>
      </div>

      <div class="form-group">
          <label class="col-md-3 control-label">RespuestaC:</label>
          <div class="col-md-9" >
            {{ Form::text('respuestaC', $question->RespuestaC,  ['class' => 'form-control'] ) }} 
          </div>
      </div>

      <div class="form-group">
          <label class="col-md-3 control-label">Introduzca la letra de la respuesta correcta:</label>
          <div class="col-md-9" >
            {{ Form::text('respuestaCorrecta', $question->Resp_Correcta,  ['class' => 'form-control'] ) }}
          </div>
      </div>
      <div class="form-group">
         {{ Form::submit('Guardar Pregunta',array('class'=>'btn purple')) }}
         {{ Form::reset('Reset',array('class'=>'btn btn-success')) }}
      </div> 
      </div>
    </div>
    {!! Form::close() !!}

</div>
@endsection


@section('page_script') 
   <script>
    $(document).ready(function(){
        //Actualiza el logo de la aplicacion de Videoteca
        var currentPage = window.location.href.split('/');
        var path = currentPage[0].split('.')[0] + '//' + currentPage[2].split('.')[0];
        var urlLogo = path + '/assets/layouts/layout6/img/logo1.png';
        $('#logoVideoteca').attr('src', urlLogo);

    });
</script>
@endsection

resources/views/pregunta/loadPregunta.blade.php
		<table class="table table-striped table-bordered table-hover"" id="tblCuestionario">
			<thead>
				<tr>
				  	<th>N°</th>
				  	<th>Cuestionario</th>
					<th>Pregunta</th>
					<th align="center">Respuesta Correcta</th>
					<th align="center">Editar</th>
					<th align="center"></th>
				</tr>
			</thead>
			<tbody>
				@foreach($preguntas as $item)
				<tr>
				  <td>{{ $item->idPregunta }}</td>
				  <td>{{ $item->Titulo }}</td>
				  <td>{{ $item->Pregunta }}</td>
				  <td align="center">{{ $item->Resp_Correcta }}</td>
				  <td align="center"> <a href="{{ route('pregunta.show', $item->idPregunta ) }}">  <span class="sub_icon glyphicon glyphicon-file"> </td>
				  <td align="center">
				  {!! Form::open([
			            'method' => 'DELETE',
			            'route' => ['pregunta.destroy', $item->idPregunta]
			       ]) !!}
			       {!! Form::submit('Eliminar', ['class' => 'btn btn-warning']) !!}
			      {!! Form::close() !!} 
			      </td>
				</tr>
				@endforeach
			</tbody>
		</table>
		<div class="form-group">
			<table>
				<thead>
					<tr>
						<th></th>
						<th></th>
					</tr>
					</thead>
					<tbody>
						<tr>
							<td>{{ $preguntas->links() }}</td>
							<td  align="right">
								{{ $preguntas->firstItem() }} de {{ $preguntas->count() }} en total {{ $preguntas->total() }}
							</td>
							<!--
							<td></td>
							<td>
								<div class="text-right">
							  		<a href="{{ route('clasificacionVideo.create', []) }}" class="btn btn-circle blue-steel">Agregar clasificacion <i class="fa fa-plus"></i></a>
							  	</div>
							</td>
							-->
						</tr>
					</tbody>
			</table>
						 
			@if(Session::has('success'))
			   <div class="alert alert-success">
			        {{ Session::get('success') }}
			    </div>
			@endif
		</div>
</div>

resources/views/pregunta/viewIndex.blade.php
@extends('layouts.master')
@section('title', 'BioVideoteca >> Listado de Preguntas')
@section('breadcrumbs')
@endsections
@section('content')

<div class="portlet box purple">
    <div class="portlet-title">
	    <div class="caption">
	      <i class="fa fa-gift"></i>Listado de Preguntas
	    </div>
    </div>
 
<div class="portlet-body">
	<div class="panel-body">
					{!! Form::open(['route'=> 'pregunta.index', 'method'=> 'GET', 'class'=> 'navbar-form navbar-left pull-right', 'role'=> 'search']) !!}
						<div class="form-group">
							{!! Form::text('titulo', null, ['class' => 'form-control', 'placeholder' => 'Buscar por cuestionario' ]) !!}
						</div>
						<button type="submit" class="btn btn-default">Buscar</button>
					{!! Form::close() !!}
	</div>
	<div class="table-responsive">

	@if($preguntas->count())
		@include('pregunta.loadPregunta')
	@else
		<h2>No se encontraron preguntadas registradas</h2>
	@endif
	
</div>	
@endsection

@section('page_script')	
	<script>
	$(document).ready(function(){
		
        //Actualiza el logo de la aplicacion de Videoteca
        var currentPage = window.location.href.split('/');
        var path = currentPage[0].split('.')[0] + '//' + currentPage[2].split('.')[0];
        var urlLogo = path + '/assets/layouts/layout6/img/logo1.png';
        $('#logoVideoteca').attr('src', urlLogo);

		$(document).on('click','.pagination a', function(e){
			e.preventDefault();
			var url = $(this).attr('href');
			getPreguntas(url);
		});
	});

	function getPreguntas(url){

		$.ajax({
			url: url
		}).done(function(data){
			$('.table-responsive').html(data);
			//console.log(data);
			
		}).fail(function (){
			alert('No se pudo leer la informacion');
		});

	}
		
	</script>
@endsection